export const constants = {
    GET_NAME_REQUEST: 'GET_NAME_REQUEST',
    GET_NAME_SUCCESS: 'GET_NAME_SUCCESS',
    GET_NAME_FAILURE: 'GET_NAME_FAILURE',

        GET_DISTANCE_REQUEST: 'GET_DISTANCE_REQUEST',
    GET_DISTANCE_SUCCESS: 'GET_DISTANCE_SUCCESS',
    GET_DISTANCE_FAILURE: 'GET_DISTANCE_FAILURE',
}